[package]
name = "rusty_cms"
version = "0.1.0"
authors = ["Fx137 <flufeu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "*"
hyper = "0.14.10"
mime = "0.3.16"
comrak = "0.10.1"
regex = "1"