# alpine
FROM alpine:latest
LABEL Name=rusty_cms Version=0.0.1
RUN apk --no-cache add curl
RUN apk add build-base
RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- --default-toolchain stable -y
WORKDIR /rusty_cms
EXPOSE 7878
COPY . .
RUN $HOME/.cargo/bin/cargo install --path .
CMD ["target/release/rusty_cms"]



# rust
FROM rust:latest
LABEL Name=rusty_cms Version=0.0.1
WORKDIR /rusty_cms
EXPOSE 7878
COPY . .
RUN cargo install --path .
CMD ["rusty_cms"]



# minimal
FROM rust:latest AS build
WORKDIR /usr/src
RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /app
COPY . .
RUN cargo install --target x86_64-unknown-linux-musl --path .

FROM scratch
COPY --from=build /usr/local/cargo/bin/rusty_cms .
USER 1000
EXPOSE 7878
RUN ls
CMD ["./rusty_cms"]
